/**
 * @fileoverview WhatsApp Marketing System — Core TypeScript Types
 *
 * Covers all domain entities: brands, contacts, messages, conversations,
 * campaigns, drip sequences, templates, and analytics aggregates.
 *
 * @module types/whatsapp
 */

// ─────────────────────────────────────────────────────────────────────────────
// Brand
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Configuration for a single brand that owns a WhatsApp number.
 * Drives outbound message routing and AI persona.
 */
export interface BrandConfig {
  /** Stable identifier — used as FK throughout the system */
  id: 'kalisiya' | 'eloi' | 'datamug';
  /** Human-readable display name */
  name: string;
  /** Short description shown in the UI */
  description: string;
  /** E.164-formatted WhatsApp number (e.g. +917794911850) */
  whatsappNumber: string;
  /** Full system prompt passed to the AI responder */
  systemPrompt: string;
  /** List of products/services the brand offers */
  services: string[];
  /** Description of the brand's target audience */
  targetAudience: string;
  /** Desired conversational tone for AI responses */
  tone: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Contact / Lead
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A contact (lead) stored in the CRM.
 * One contact can belong to only one brand at a time.
 */
export interface Contact {
  /** UUID v4 */
  id: string;
  /** E.164 phone number */
  phone: string;
  /** Full name */
  name: string;
  /** Optional email address */
  email?: string;
  /** Optional company/organisation name */
  company?: string;
  /** Job title or role */
  role?: string;
  /** Which brand this contact belongs to */
  brand: BrandConfig['id'];
  /** Free-form segmentation tags (e.g. "donor", "enterprise", "trial") */
  tags: string[];
  /**
   * Engagement-based lead score, 0–100.
   * Automatically incremented by CRM engagement events.
   */
  leadScore: number;
  /** Funnel stage */
  stage: 'new' | 'contacted' | 'engaged' | 'qualified' | 'converted' | 'lost';
  /** How the contact entered the system */
  source: 'import' | 'manual' | 'inbound' | 'campaign';
  /** Free-form internal notes */
  notes: string;
  /** ISO 8601 timestamp of the last outbound or inbound message */
  lastContacted?: string;
  /** ISO 8601 creation timestamp */
  createdAt: string;
  /** ISO 8601 last-updated timestamp */
  updatedAt: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Conversation & Messages
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A single WhatsApp message — either inbound (from the contact)
 * or outbound (sent by the system or a human agent).
 */
export interface Message {
  /** UUID v4 */
  id: string;
  /** The contact this message belongs to */
  contactId: string;
  /** Whether the message was received from or sent to the contact */
  direction: 'inbound' | 'outbound';
  /** Plain-text or template-rendered message body */
  body: string;
  /** Optional media attachment URL */
  mediaUrl?: string;
  /** Twilio delivery state */
  status: 'queued' | 'sent' | 'delivered' | 'read' | 'failed';
  /** Twilio Message SID (populated once sent) */
  twilioSid?: string;
  /** Which brand's number was used */
  brand: BrandConfig['id'];
  /** True when the body was generated by the AI responder */
  isAiGenerated: boolean;
  /** ISO 8601 timestamp */
  timestamp: string;
}

/**
 * Aggregated view of all messages between the system and a single contact.
 */
export interface Conversation {
  /** FK to Contact.id */
  contactId: string;
  /** Chronologically ordered message array */
  messages: Message[];
  /** Shortcut to the most recent message */
  lastMessage?: Message;
  /** Count of inbound messages not yet read by an agent */
  unreadCount: number;
  /** Whether the conversation is open (not archived/resolved) */
  isActive: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// Templates & Campaigns
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Reusable message template.
 * Supports Handlebars-style placeholders: {{name}}, {{company}},
 * {{service}}, {{brand}}.
 */
export interface MessageTemplate {
  /** UUID v4 */
  id: string;
  /** Human-readable label */
  name: string;
  /**
   * Message body with optional {{placeholder}} tokens.
   * Rendered at send time by the campaign engine.
   */
  body: string;
  /** Owning brand */
  brand: BrandConfig['id'];
  /** Functional category for filtering / analytics */
  category: 'welcome' | 'followup' | 'promotion' | 'newsletter' | 'custom';
  /** ISO 8601 creation timestamp */
  createdAt: string;
}

/**
 * A bulk-send campaign targeting a subset of contacts via a template.
 */
export interface Campaign {
  /** UUID v4 */
  id: string;
  /** Human-readable campaign name */
  name: string;
  /** Owning brand */
  brand: BrandConfig['id'];
  /** Which template to send */
  templateId: string;
  /** Lifecycle status */
  status: 'draft' | 'scheduled' | 'running' | 'paused' | 'completed';
  /**
   * Only contacts with at least one of these tags are included.
   * Empty array = all contacts for the brand.
   */
  targetTags: string[];
  /**
   * Only contacts in these funnel stages are included.
   * Empty array = all stages.
   */
  targetStages: Contact['stage'][];
  /** ISO 8601 — when to start sending (null = send immediately) */
  scheduledAt?: string;
  /** Running total of messages sent */
  sentCount: number;
  /** Running total of messages confirmed delivered */
  deliveredCount: number;
  /** Running total of messages confirmed read */
  readCount: number;
  /** Running total of contacts who replied */
  repliedCount: number;
  /** ISO 8601 creation timestamp */
  createdAt: string;
  /** ISO 8601 last-updated timestamp */
  updatedAt: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Drip Sequences
// ─────────────────────────────────────────────────────────────────────────────

/**
 * One step in an automated drip sequence.
 */
export interface DripStep {
  /** UUID v4 */
  id: string;
  /** Template to send at this step */
  templateId: string;
  /** Days to wait after the previous step (or enrolment for step 1) */
  delayDays: number;
  /**
   * Conditional trigger:
   * - 'no_reply'  — only advance if the contact has NOT replied
   * - 'replied'   — only advance if the contact HAS replied
   * - 'any'       — always advance (default)
   */
  condition?: 'no_reply' | 'replied' | 'any';
}

/**
 * An ordered collection of drip steps that can be enrolled to contacts.
 */
export interface DripSequence {
  /** UUID v4 */
  id: string;
  /** Human-readable sequence name */
  name: string;
  /** Owning brand */
  brand: BrandConfig['id'];
  /** Ordered array of steps */
  steps: DripStep[];
  /** Whether new contacts can be enrolled */
  isActive: boolean;
  /** Contact IDs currently enrolled in this sequence */
  enrolledContacts: string[];
  /** ISO 8601 creation timestamp */
  createdAt: string;
}

/**
 * Tracks an individual contact's progress through a drip sequence.
 */
export interface DripEnrollment {
  /** UUID v4 */
  id: string;
  /** FK to DripSequence.id */
  sequenceId: string;
  /** FK to Contact.id */
  contactId: string;
  /** Zero-based index of the next step to execute */
  currentStepIndex: number;
  /** ISO 8601 — when to send the next step */
  nextSendAt: string;
  /** Whether this enrollment is still active */
  isActive: boolean;
  /** ISO 8601 enrolment timestamp */
  enrolledAt: string;
  /** ISO 8601 completion/exit timestamp */
  completedAt?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Analytics
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Aggregated analytics snapshot for the WhatsApp marketing system.
 * Computed on-demand from the underlying JSON stores.
 */
export interface WhatsAppAnalytics {
  /** Total number of contacts across all brands */
  totalContacts: number;
  /** Conversations with at least one message in the last 7 days */
  activeConversations: number;
  /** Cumulative outbound message count */
  messagesSent: number;
  /** Cumulative inbound message count */
  messagesReceived: number;
  /** Fraction of sent messages confirmed delivered (0–1) */
  deliveryRate: number;
  /** Fraction of delivered messages confirmed read (0–1) */
  readRate: number;
  /** Fraction of delivered messages that received a reply (0–1) */
  replyRate: number;
  /** Number of campaigns with status 'completed' or 'running' */
  campaignsSent: number;
  /** Most-used contact tags, sorted descending by count */
  topTags: { tag: string; count: number }[];
  /** Contact count per funnel stage */
  stageDistribution: { stage: string; count: number }[];
  /** Per-brand breakdown of contacts and message volume */
  brandBreakdown: { brand: string; contacts: number; messages: number }[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Utility / Internal
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Result shape returned by AI intent detection inside ai-responder.
 */
export interface IntentResult {
  /**
   * Primary intent category:
   * - 'inquiry'    — asking about a service/product
   * - 'pricing'    — asking about cost / pricing
   * - 'demo'       — requesting a demo or trial
   * - 'complaint'  — expressing dissatisfaction
   * - 'optout'     — asking to stop receiving messages
   * - 'greeting'   — general greeting / small talk
   * - 'unknown'    — could not be determined
   */
  intent: 'inquiry' | 'pricing' | 'demo' | 'complaint' | 'optout' | 'greeting' | 'unknown';
  /** Confidence score 0–1 */
  confidence: number;
  /** Suggested next action for the agent or automation */
  suggestedAction: 'reply' | 'schedule_call' | 'send_brochure' | 'escalate' | 'unsubscribe';
}

/**
 * Lead-scoring event logged when contact engagement changes.
 */
export interface LeadScoringEvent {
  /** The type of engagement that occurred */
  event:
    | 'message_received'   // +10
    | 'replied'            // +20
    | 'link_clicked'       // +15
    | 'demo_requested'     // +25
    | 'phone_call'         // +30
    | 'unsubscribed'       // −50
    | 'no_reply_7d';       // −5
  /** Point delta (positive or negative) */
  delta: number;
  /** ISO 8601 timestamp */
  occurredAt: string;
}

/**
 * Data shape for parsed CSV import rows.
 */
export interface CsvContactRow {
  name: string;
  phone: string;
  email?: string;
  company?: string;
  role?: string;
  tags?: string;   // comma-separated string in the CSV
  notes?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Multi-Channel Outreach
// ─────────────────────────────────────────────────────────────────────────────
// Note: Contact already has `email?: string` (see line ~53).
// The `telegramChatId` field below is added to outreach messages only;
// it can be stored on Contact.notes or a future Contact extension.

/**
 * Supported outreach delivery channels.
 * - 'email'    — Brevo transactional email
 * - 'telegram' — Telegram Bot API
 * - 'whatsapp' — Meta WhatsApp Cloud API (separate from Twilio)
 * - 'sms'      — Reserved for future SMS channel
 */
export type OutreachChannel = 'email' | 'telegram' | 'whatsapp' | 'sms';

/**
 * A single outreach message dispatched (or queued) to one contact
 * via one channel.  One record is created per send attempt.
 */
export interface OutreachMessage {
  /** UUID v4 */
  id: string;
  /** Which delivery channel was used */
  channel: OutreachChannel;
  /** FK to Contact.id */
  contactId: string;
  /**
   * Destination address — interpretation varies by channel:
   * - email    → email address
   * - telegram → Telegram chat ID
   * - whatsapp → E.164 phone number
   * - sms      → E.164 phone number
   */
  to: string;
  /** Email subject line (email channel only) */
  subject?: string;
  /** Plain-text message body */
  body: string;
  /** HTML body (email channel only) */
  htmlBody?: string;
  /** Current delivery lifecycle status */
  status: 'queued' | 'sent' | 'delivered' | 'failed';
  /** Provider-assigned message ID (Brevo messageId, Telegram message_id, Meta WAMID) */
  externalId?: string;
  /** Human-readable error description when status === 'failed' */
  error?: string;
  /** Which brand sent this message */
  brand: 'kalisiya' | 'eloi' | 'datamug';
  /** ISO 8601 timestamp of when the message was successfully sent */
  sentAt?: string;
  /** ISO 8601 creation timestamp */
  createdAt: string;
}

/**
 * A bulk outreach campaign that targets a filtered subset of contacts
 * and sends the same message to all of them via a single channel.
 */
export interface OutreachCampaign {
  /** UUID v4 */
  id: string;
  /** Human-readable campaign name */
  name: string;
  /** Delivery channel for the entire campaign */
  channel: OutreachChannel;
  /** Owning brand */
  brand: 'kalisiya' | 'eloi' | 'datamug';
  /** Email subject line (email channel only) */
  subject?: string;
  /** Plain-text message body */
  body: string;
  /** HTML body (email channel only) */
  htmlBody?: string;
  /** Campaign lifecycle status */
  status: 'draft' | 'running' | 'completed' | 'failed';
  /**
   * Only contacts with at least one of these tags are included.
   * Empty array = no tag filter (all contacts for the brand).
   */
  targetTags: string[];
  /**
   * Only contacts in these funnel stages are included.
   * Empty array = all stages.
   */
  targetStages: string[];
  /** Total number of contacts targeted by this campaign */
  totalRecipients: number;
  /** Running count of messages successfully sent */
  sentCount: number;
  /** Running count of messages confirmed delivered */
  deliveredCount: number;
  /** Running count of messages that failed to send */
  failedCount: number;
  /** ISO 8601 creation timestamp */
  createdAt: string;
  /** ISO 8601 last-updated timestamp */
  updatedAt: string;
}
